
networks:
  opendaoc-network:
    driver: bridge

volumes:
  openbots-db-data:
  base-db:

services:
  db:
    image: mariadb:11
    container_name: openbots-db
    stdin_open: true
    tty: true
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --character-set-server=utf8mb3 --collation-server=utf8mb3_general_ci --innodb_large_prefix=1 --innodb_file_per_table=1
    restart: always
    environment:
      MYSQL_DATABASE: opendaoc
      MYSQL_ROOT_PASSWORD: 8I9ehCOtu20cQm8
    volumes:
      - openbots-db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - opendaoc-network

  gameserver:
    build: .                                    # ← BUILD LOCAL SinglePlayerBots
    container_name: openbots-server
    stdin_open: true
    tty: true
    ports:
      - "10300:10300"
      - "10300:10300/udp"
      - "10400:10400"
      - "10400:10400/udp"
    depends_on:
      - db
    environment:
      UID: "1000"
      GID: "1000"
      AUTO_ACCOUNT_CREATION: "True"
      CHEAT_LOGGER_NAME: "cheats"
      CPU_USE: "8"
      DB_AUTOSAVE: "True"
      DB_AUTOSAVE_INTERVAL: "10"
      DB_CONNECTION_STRING: "server=db;port=3306;database=opendaoc;userid=root;password=8I9ehCOtu20cQm8;treattinyasboolean=true"
      DB_TYPE: "MYSQL"
      DETECT_REGION_IP: "True"
      ENABLE_COMPILATION: "False"
      ENABLE_UPNP: "False"
      GAME_TYPE: "PvP"
      GM_ACTION_LOGGER_NAME: "gmactions"
      INVALID_NAMES_FILE: "./config/invalidnames.txt"
      LOG_CONFIG_FILE: "./config/logconfig.xml"
      REGION_IP: "0.0.0.0"
      REGION_PORT: "10400"
      SCRIPT_ASSEMBLIES: ""
      SCRIPT_COMPILATION_TARGET: "./lib/GameServerScripts.dll"
      SERVER_IP: "0.0.0.0"
      SERVER_NAME: "OpenDAoC"
      SERVER_NAME_SHORT: "OPENDAOC"
      SERVER_PORT: "10300"
      UDP_IP: "0.0.0.0"
      UDP_PORT: "10400"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT_MODE: "false"
    volumes:
      - ./db-init:/tmp/opendaoc-db:ro
    networks:
      - opendaoc-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: openbots-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 8I9ehCOtu20cQm8
    depends_on:
      - db
    networks:
      - opendaoc-network
