UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Loras' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant K' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Skin2' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Tywinn' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'John' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Joric' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Stellan' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Rhaegar' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Azzura' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Skin4' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Leag Ulvir' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Borin Thekesd' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Skin3' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Zog' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Alienor' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Orn' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant G' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant A' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Capitaine Némo' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Eldrin' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Helga' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Lineat' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Stanislas' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Korgan' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'feu vif' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant S' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Grond' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant W' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Fendrel' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Henry' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Ingrid Lemouton' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'feu doux' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Kilote' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Orik' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Selrien' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Lorian' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant Z' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Krunk' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Stèle du Souvenir' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Snarg' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Dori' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Marmitte chaude' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Valgard' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Ame torturée' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Torvald' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Nabucar' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Anspic' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant L' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Erion' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Mischa' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Laerea' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Isira' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Thorek Sek' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Source d\\' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Mardona' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Clovis Leclou' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant I' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Pellys' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Stengrim' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Ulrik' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Kliomo' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Corbin' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Dunar' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Marguerite' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Sapharin' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Vorion' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Savant R' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Phyl' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Gauvain' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Radius' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'feu moyen' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Arazae' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Theron' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Meliop' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Asbeth' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Odor Thedoor' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Sybil' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Gunnar' AND Region = 51;
UPDATE mob SET ClassType = 'DOL.GS.Scripts.AvalonExchangerNPC' WHERE Name = 'Raelson' AND Region = 51;
